language: python

services:
  - docker

install:
  - make deps
script:
  - make test
  - make lint
  - make docker_build
  - make docker_push

deploy:
    provider: heroku
    app: enigmatic-island-96392
    api_key: ${HEROKU_API_KEY}
